name: Documentation Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  document:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup GitHub Copilot CLI
      run: |
        npm install -g @githubnext/github-copilot-cli
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Documentation Coverage
      run: |
        # Check for docstrings and documentation in Python files
        python -m doctest **/*.py
        python -m pydoc -w .

    - name: Generate Documentation Updates
      run: |
        # Use GitHub Copilot to suggest documentation improvements
        gh copilot suggest "Review and improve documentation in:"
        find . -type f -name "*.py" -exec gh copilot suggest "Improve documentation in {}" \;
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate Model Cards
      run: |
        # Run our model card validator on all .md files in model_cards directory
        python tools/validators/model_card_validator.py implementation/model_cards/*.md

    - name: Update Progress Tracking
      run: |
        # Update PROGRESS.md with new changes
        python tools/update_progress.py

    - name: Create Documentation PR
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "docs: Update documentation with Copilot suggestions"
        title: "Documentation Updates"
        body: |
          This PR contains automated documentation updates generated with GitHub Copilot assistance.
          
          Changes include:
          - Documentation coverage improvements
          - Model card validations
          - Progress tracking updates
          
          Please review the changes and merge if appropriate.
        branch: docs/automated-updates
        delete-branch: true
        labels: documentation

    - name: Check Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        folder-path: '.'

    - name: Run markdownlint
      uses: nosborn/github-action-markdown-cli@v3.3.0
      with:
        files: .
        config: .markdownlint.json
        ignore: node_modules

    - name: Generate Documentation Site
      run: |
        # Build documentation site using mkdocs
        mkdocs build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Documentation Workflow Failed',
            body: 'The documentation automation workflow has failed. Please check the logs for more details.'
          })
