name: Learning Documentation Update

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:         # Manual trigger option

jobs:
  document:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0     # Get full history for better documentation
          
      - name: Update and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Get timestamp for commit message
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Add all changes
          git add .
          
          # Commit with detailed message including timestamp
          git commit -m "Learning Progress Update: $TIMESTAMP
          
          Documentation Updates:
          - Updated README and learning notes
          - Tracked progress in Qwen2.5-VL understanding
          - Captured new insights and examples" || echo "No changes to commit"
          
          # Push changes
          git push
